# Generated by Django 3.1.1 on 2024-04-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveduniversity',
            name='rating',
        ),
    ]
