# Generated by Django 3.1.1 on 2024-04-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_remove_saveduniversity_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveduniversity',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
