# Generated by Django 3.1.1 on 2024-05-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='content',
        ),
    ]
