# Generated by Django 3.1.1 on 2024-05-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_auto_20240509_1942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
    ]
